CREATE TABLE pokémon(
    index_number Integer(9) not null,
    dex_number integer(9) not null,
    pokémon_name varchar(30) not null,
    japanese_name varchar(30),
    generation int(2) not null,
    legend_status varchar(30) not null,
    category varchar(30) not null,
    type_number varchar(1),
    type1 varchar(30) not null,
    type2 varchar(30),
    height_m double not null,
    weight_kg double not null,
    abilities_number integer(1),
    ability1 varchar(30),
    ability2 varchar(30),
    ability_hidden varchar(30),
    points_total integer(10),
   hp integer(10),
   attack integer(10),
   defense integer(10),
   special_attack integer(10),
   special_defense integer(10),
   speed integer(10),
   catch_rate integer(10),
   base_friendship integer(10),
   base_experience integer(10),
   growth_rate varchar(30),
   number_egg_group integer(10),
   egg_group_1 varchar(30),
   egg_group_2 varchar(30),
   percent_male double,
   egg_cycles integer(20),
   against_normal double,
   against_fire double,
   against_water double,
   against_electric double,
   against_grass double,
   against_ice double,
   against_fighting double,
   against_poison double,
   against_ground double,
   against_flying double,
   against_psychic double,
   against_bug double,
   against_rock double,
   against_ghost double,
   against_dragon double,
   against_dark double,
   against_steel double,
   against_fairy double,
   german_name varchar(30),
   primary key(index_number)
);

LOAD DATA LOCAL INFILE "C:/Users/demur/Documents/Coding/Practice Code/Full Stack Pokemon App/CSV_Raw_Data/gen8dex.csv"
INTO TABLE Pokémon
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

DROP TABLE pokémon;